{{- if not .Values.existingSecretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tiger2048.fullname" . }}
  labels:
    app: {{ include "tiger2048.name" . }}
    chart: {{ include "tiger2048.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  exampleSecret: {{ .Values.secrets.exampleSecret | b64enc }}
{{- end }}
