{{- if and .Values.tls.certificate .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  {{- if  .Values.ingress.secretName }}
  name: {{ .Values.ingress.secretName }}
  {{- else }}
  name: {{ include "tiger2048.fullname" . }}-tls
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certificate | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
{{- end }}
