# Default values for tiger2048.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

clusterEnv: development

image:
  repository: x46085/tiger2048
  pullPolicy: IfNotPresent

  # If a digest is provided it takes precedence over a tag. Both of these
  # should be set to a fixed value before packaging a chart.
  tag: ""
  digest: ""

nameOverride: ""
fullnameOverride: ""

existingSecretName: ~

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# If provided, a TLS secret is created from these values and saved to
# .Values.ingress.secretName if it is defined, falling back to
# `{{ include "tiger2048.fullname" . }}-tls`
tls: {}
# certificate: ...
# key: ...

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
